In [2]:
import numpy as np

In [23]:
arr=np.array([[1,2,5],[2,3,4]])
print((arr).shape)

(2, 3)


In [38]:
arr1=np.ones((2,3),dtype="int64")
print(arr1)
arr2=np.full((3,4),100)
print(arr2)
print(np.eye(3))
print(np.linspace(0,100,4))

print(arr.size)

[[1 1 1]
 [1 1 1]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[  0.          33.33333333  66.66666667 100.        ]
6


In [40]:
arr3=np.array([1,2,3,4])
f_arr=arr3.astype(np.float64)
print(f_arr)

[1. 2. 3. 4.]


In [41]:
li=[1,2,3,4]
na=np.array(li)
print(na)

[1 2 3 4]


In [45]:
lo=na.tolist()
print(type(lo))
print(type(na))

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
#operations on arrays
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [6]:
reshaped=arr.reshape((1,6))
print(reshaped)

[[1 2 3 4 5 6]]


In [8]:
flattened=arr.flatten()
print(flattened)

[1 2 3 4 5 6]


In [10]:
#Indexing
arr=np.array([[1,2,3,4,5],[1,2,4,6,7]])
print(arr[1][4])

7


In [12]:
arr=np.array([1,2,3,4,5])
print(arr[[1,2,3]])

[2 3 4]


In [14]:
arr=np.array([1,2,3,4,5])
print(arr[arr>3])

[4 5]


In [23]:
#Slicing
arr=np.array([1,2,3,4,5])
print(arr[1:4:2])

[2 4]


In [25]:
print(arr.dtype)

int64


In [26]:
arr=np.array([1,1+7j])
print(arr.dtype)

complex128


In [27]:
print(arr)

[1.+0.j 1.+7.j]


In [28]:
arr=np.array(["a",1,1,1,1])
print(arr.dtype)

<U21


In [29]:
print(arr)

['a' '1' '1' '1' '1']


In [32]:
#Multi-Dimensional Arrays

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
sum_of_col=np.sum(arr2D,axis=0)
print(sum_of_col)

[12 15 18]


In [33]:
#3D array
import numpy as np

arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [39]:
#vectorization
arr=np.array([1,2,3,4,5])
aq=[arr*2 if arr==1 else; for arr in arr]
print(aq)

SyntaxError: expected expression after 'else', but statement is given (757032275.py, line 3)