In [10]:
import numpy as np

In [23]:
arr=np.array([[1,2,5],[2,3,4]])
print((arr).shape)

(2, 3)


In [32]:
arr1=np.ones((2,3),dtype="int64")
print(arr1)
arr2=np.full((3,4),100)
print(arr2)

[[1 1 1]
 [1 1 1]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
