In [2]:
import numpy as np

In [23]:
arr=np.array([[1,2,5],[2,3,4]])
print((arr).shape)

(2, 3)


In [38]:
arr1=np.ones((2,3),dtype="int64")
print(arr1)
arr2=np.full((3,4),100)
print(arr2)
print(np.eye(3))
print(np.linspace(0,100,4))

print(arr.size)

[[1 1 1]
 [1 1 1]]
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[  0.          33.33333333  66.66666667 100.        ]
6


In [40]:
arr3=np.array([1,2,3,4])
f_arr=arr3.astype(np.float64)
print(f_arr)

[1. 2. 3. 4.]


In [41]:
li=[1,2,3,4]
na=np.array(li)
print(na)

[1 2 3 4]


In [45]:
lo=na.tolist()
print(type(lo))
print(type(na))

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
#operations on arrays
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [6]:
reshaped=arr.reshape((1,6))
print(reshaped)

[[1 2 3 4 5 6]]


In [8]:
flattened=arr.flatten()
print(flattened)

[1 2 3 4 5 6]


In [10]:
#Indexing
arr=np.array([[1,2,3,4,5],[1,2,4,6,7]])
print(arr[1][4])

7


In [12]:
arr=np.array([1,2,3,4,5])
print(arr[[1,2,3]])

[2 3 4]


In [14]:
arr=np.array([1,2,3,4,5])
print(arr[arr>3])

[4 5]


In [23]:
#Slicing
arr=np.array([1,2,3,4,5])
print(arr[1:4:2])

[2 4]


In [25]:
print(arr.dtype)

int64


In [26]:
arr=np.array([1,1+7j])
print(arr.dtype)

complex128


In [27]:
print(arr)

[1.+0.j 1.+7.j]


In [28]:
arr=np.array(["a",1,1,1,1])
print(arr.dtype)

<U21


In [29]:
print(arr)

['a' '1' '1' '1' '1']


In [32]:
#Multi-Dimensional Arrays

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
sum_of_col=np.sum(arr2D,axis=0)
print(sum_of_col)

[12 15 18]


In [33]:
#3D array
import numpy as np

arr = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [40]:
#vectorization
arr=np.array([1,2,3,4,5])
print(arr**2)
print(arr+2)

[ 1  4  9 16 25]
[3 4 5 6 7]


In [45]:
#broadcasting
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3,4,5],[3,4,5,6,7]])
print(arr1+arr2)

[[ 2  4  6  8 10]
 [ 4  6  8 10 12]]


In [53]:
#Normalization
arr1=np.array([[1,2],[3,4]])
mean=(np.mean(arr1))
std_dev=(np.std(arr1))

normalized_arr=(arr-mean)/std_dev
print(normalized_arr)

[-1.34164079 -0.4472136   0.4472136   1.34164079  2.23606798]


In [81]:
# np functions
arr=np.array([1,2,3,4,5,3])
print(np.sum(arr1))
print(np.prod(arr1))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

# Log
print(np.log(arr))
print(np.log10(arr))
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

#rounding
print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

15
120
1
5
0
4
3.0
1.2909944487358056
3.0
1.6666666666666667
[ 1  4  9 16 25  9]
[1.         1.41421356 1.73205081 2.         2.23606798 1.73205081]
[  1   8  27  64 125  27]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.09861229]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.47712125]
[1 2 3 4 5]
[1 2 3 3 4 5]
[1 2 3 4 5 3]
3.0
4.0
3.0
3.0
